# MongoDB Configuration
mongodb:
  connections:
    primary:
      uri: "${MONGODB_PRIMARY_URI}"
      retry:
        max_attempts: 3
        delay_seconds: 5
      sources:
        users:
          database: "${MONGODB_USERS_DB}"
          collection: "${MONGODB_USERS_COLLECTION}"
          batch_size: 100
        orders:
          database: "${MONGODB_ORDERS_DB}"
          collection: "${MONGODB_ORDERS_COLLECTION}"
          batch_size: 200
    analytics:
      uri: "${MONGODB_ANALYTICS_URI}"
      retry:
        max_attempts: 3
        delay_seconds: 5
      sources:
        metrics:
          database: "${MONGODB_ANALYTICS_DB}"
          collection: "${MONGODB_ANALYTICS_COLLECTION}"
          batch_size: 500

# Google Cloud Configuration
gcp:
  project_id: "${GCP_PROJECT_ID}"
  region: "${GCP_REGION}"
  
  # Pub/Sub Configuration
  pubsub:
    topics:
      users: "${PUBSUB_USERS_TOPIC}"
      orders: "${PUBSUB_ORDERS_TOPIC}"
      metrics: "${PUBSUB_METRICS_TOPIC}"
    dead_letter_topic: "${DEAD_LETTER_TOPIC}"

# Monitoring Configuration
monitoring:
  health_check_interval: 60  # seconds
  connection_timeout: 5000   # milliseconds

# Error Handling
error_handling:
  max_retries: 3
  backoff_factor: 2  # exponential backoff multiplier

# Streaming Configuration
streaming:
  batch_size: 100  # Number of documents to process in each batch
  window_size_seconds: 60  # Window size for processing batches 